# Shell variables
# Generated by 'wal'
wallpaper='maki.png'

# Special
background='#161a1e'
foreground='#fffaf8'
cursor='#fffaf8'

# Colors
color0='#161a1e'
color1='#ab4550'
color2='#959eaa'
color3='#7093aa'
color4='#b0b0b0'
color5='#c63a43'
color6='#c78c8b'
color7='#e2d8d6'
color8='#262d35'
color9='#ed4a5b'
color10='#adcaf1'
color11='#7fc2ef'
color12='#fbcece'
color13='#ff3a48'
color14='#ffa09e'
color15='#fffaf8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
