# Shell variables
# Generated by 'wal'
wallpaper='proxy.duckduckgo.com.jpg'

# Special
background='#231f1d'
foreground='#c8c7c6'
cursor='#c8c7c6'

# Colors
color0='#231f1d'
color1='#c3bdbc'
color2='#c5a898'
color3='#ab9670'
color4='#a3a49d'
color5='#7ec199'
color6='#5caa7f'
color7='#c8c7c6'
color8='#5a5755'
color9='#c3bdbc'
color10='#c5a898'
color11='#ab9670'
color12='#a3a49d'
color13='#7ec199'
color14='#5caa7f'
color15='#c8c7c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
