# Shell variables
# Generated by 'wal'
wallpaper='thumb-1920-858933.jpg'

# Special
background='#151621'
foreground='#c4c4c7'
cursor='#c4c4c7'

# Colors
color0='#151621'
color1='#7688c4'
color2='#5a60b6'
color3='#c2b5bd'
color4='#b05b82'
color5='#b0224e'
color6='#c38d8e'
color7='#c4c4c7'
color8='#4f5058'
color9='#7688c4'
color10='#5a60b6'
color11='#c2b5bd'
color12='#b05b82'
color13='#b0224e'
color14='#c38d8e'
color15='#c4c4c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
